### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by shri30yans**
Signed-off-by: Shriyans Gandhi <41372639+shri30yans@users.noreply.github.com>

## Summary

Fixes the spelling of "package" in the readme.md

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Dhruvacube** [comment]
uhhhhhh hey @shri30yans i am the typo is legit but you know to me it looks 50% of the spam, i am just imagine a pr with one word change

**Comment by Dhruvacube** [comment]
so as of right now i am marking it as spam and closing this pr

**Comment by shri30yans** [comment]
@Dhruvacube Would you consider removing the "spam" label? Was looking for contributions to make for Hacktoberfest and came across your repo. Noticed the typo and made a simple PR since this repo wasn't participating. 

However, the "Spam" label counts against disqualification from the event even if it is from repo's that aren't participating. 
This has resulted in me being 1 PR away from disqualification. 

Please consider removing the label 😅. Thanks in advance.

**Comment by Dhruvacube** [comment]
nvm, well after carefull consideration i will mark this as valid because you its typo and you found it!

**Review by Dhruvacube — APPROVED** [review]

**Comment by shri30yans** [comment]
Thanks a lot. Appreciate it.

**Pull request merged**
